apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "churn"
spec:
  predictor:
    model:
      modelFormat:
        name: sklearn
      storageUri: "http://172.31.13.90:8000/model.joblib"
